###Basic config recreated for AoU usage
###Will need to modify as needed for other workspaces

basepath: "./" ##starting basepath is current dir in workflow
refloc: "./hg38.fa"
dirpath: "./"
outpath: "./output/"
dirmanifest: "examples/"
manifest_file: "manifest_example.xlsx" 
ncores: 8
aou_cram: FALSE
logout: "log_out.txt"
logerr: "log_err.txt"
script_path: "scripts/"

bed: "hg38.bed"
fasta: "hg38.fa"
target_cram: "gs://*/wgs_1000004.cram"
local_cram: "wgs_1000004.cram"
chr_loc: "chr6"
fname: "mycram"
script_name: "wgs_1000004_script.sh"

###HLA VBSeq params and processing
hlavbseq: "../../HLAVBSeq.jar"
jparam: "-Xmx12G"
process_hlas: "./script/process_hla_types.R"
allele: "./alleles.txt"
mean_cov: = "5"
read_len: "151"



