# Config for functions_hla_type.R

startpath: "/frazer01/home/aphodges/software/my_hla_typing/" 
genef: "pipeline/hla_typing/gene_info.txt"
idf: "pipeline/hla_typing/id2url.txt"
hlaset: c("HG00187", "HG01924", "HG01926", "HG01927", "NA19154")
hla_typing_path: "/frazer01/home/aphodges/software/my_hla_typing/hla_typing.sh"   
allele_path: "/frazer01/home/aphodges/software/my_hla_typing/reference/alleles.txt"       
mapx: "/frazer01/software/beagle-5.4/plink.GRCh37.map/plink.chr6.GRCh37.map"
bcftools: FALSE
myrun: "mvp"

